[_export]
;; all these values for each picture
prog_im_convert="convert"
prog_im_identify="identify"

export_folder="$basename.TP"
; parameters that can be used: (examples for source folder D:\PHOTO\EXPORT\2010\TestFolder123\ )
;	$basename 	= "TestFolder123"
;	$yearnow	= "2013"
;	$yearimg	= "2010"
;	$datenow	= "2013-06-14"
;	$dateimg	= "2010-10-01"
export_quality="95"
; 95 is OK for web publish. Use 99 if you intend to print in larger formats
export_format="jpg"
source_format="jpg,JPG"
export_width="2000"
export_height="2000"

overwrite=0
debug=0
contact_name="Tango Paparazzo"
contact_email="tangopaparazzo@gmail.com"
contact_url="http://tangopaparazzo.com"
caption="2024 www.tangopaparazzo.com - www.facebook.com/tangopaparazzo/"
event="Amarcord Marathon Bologna 2025"
tags="amarcord marathon bologna italia 2025"

;[logotp]
;gravity="SouthWest"
;image="/Users/pforret/Dropbox/PHOTO/Exports/TANGOPAPARAZZO/logos/mstf_logo/mstf_logo.png"
;resize=300
;alpha=90
;padding="30"

[copyright2]
gravity="South"
text="2025 tangopaparazzo.com"
text_color="#FFF"
text_size="24"
text_effect="shadow"
text_font="$HOME/Code/github/PaparazzoMark/font/Nunito-Bold.ttf"
padding="30"
alpha=80
